### ISSUE TITLE
animation folder doesnt grab all in the folder.

### ISSUE THREAD

**Issue by keesoudwater34** [Joschuka/fmt_mmdl#2]
just a quick one. im doing the samus animations for exporting them. and from what i can see it doesnt nab all of them in the folder. only seems to be nabbing 495 frames in total (including in the preview). and when exporting to PSK and PSA the last one in the list is " borderrecoilfrontdown " . dont know if im the only one getting that issue? having it in both FBX and PSK/PSA

It also makes me want to ask did you put an import limit on the amount of animations that can be loaded at once? due to experience with  nier automata reaching the ram limit of 32 bit noesis. they recently upgraded from there to 64 bit when it was availible. just thought i meight ask/mention that seeing there is over 4000 animations in her folder. you meight hit that cap pretty hard. ill definitely be splitting the animations in chunks when i can get this running again past that frame count.

PY Script settings :
bLoadVertexColors = True 
bShowAllMeshes = True 
bLoadAnims = True

Noesis version: 4433   32 Bit

**Comment by Joschuka** [comment]
Yeah I put a hard limit of only loading the first 20 anims, since too many people crashed the 32 bit version or complained about Noesis taking too many resources with the 64 bit version when giving the whole Samus anim folder.
Going to expose this as a parameter.

**Comment by Joschuka** [comment]
Fixed with  34b217d
Simply set the parameter at the top and you'll have as many anims loaded as you want.

**Comment by keesoudwater34** [comment]
> Fixed with [34b217d](https://github.com/Joschuka/fmt_mmdl/commit/34b217d36953095f61316e0dd742696e9d6a931c) Simply set the parameter at the top and you'll have as many anims loaded as you want.

thank you for making that a parameter seriously. doing 4600 and then 20 at a time is gonna take forever so seriously thank you!

**Comment by keesoudwater34** [comment]
was able to do 500/600 at a time with psk and psa no issues. in 10 chunks it was done. thought i should tell it worked.
